# Generated by Django 5.2.8 on 2025-11-26 03:55

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SyncResults",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="created_at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "new_events_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of new events created during sync",
                        verbose_name="new_events_count",
                    ),
                ),
                (
                    "updated_events_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of events updated during sync",
                        verbose_name="updated_events_count",
                    ),
                ),
                (
                    "last_synced_changed_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Date of the last synced event's changed_at field",
                        null=True,
                        verbose_name="last_synced_changed_at",
                    ),
                ),
            ],
            options={
                "verbose_name": "sync_result",
                "verbose_name_plural": "sync_results",
                "db_table": "sync_results",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="idx_sync_created_at"),
                ],
            },
        ),
    ]
