# Generated by Django 5.2.8 on 2025-11-27 03:46

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotificationModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        db_index=True,
                        help_text="The topic/channel where the notification should be published",
                        max_length=255,
                        verbose_name="topic",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        help_text="The notification payload data",
                        verbose_name="payload",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="created_at",
                    ),
                ),
                (
                    "sent",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether the notification has been sent",
                        verbose_name="sent",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the notification was sent",
                        null=True,
                        verbose_name="sent_at",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["sent", "-created_at"],
                        name="idx_notification_sent_created",
                    ),
                    models.Index(
                        fields=["topic", "-created_at"],
                        name="idx_notification_topic_created",
                    ),
                ],
            },
        ),
    ]
