# Generated by Django 5.2.8 on 2025-11-27 03:46

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventAreaModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the event area",
                        max_length=255,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="created_at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
            ],
            options={
                "verbose_name": "event_area",
                "verbose_name_plural": "event_areas",
                "db_table": "event_areas",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="idx_name"),
                    models.Index(fields=["-created_at"], name="idx_area_created_at"),
                ],
            },
        ),
        migrations.CreateModel(
            name="EventModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the event",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "registration_deadline",
                    models.DateTimeField(
                        db_index=True,
                        verbose_name="registration_deadline",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        db_index=True,
                        default="open",
                        help_text="Current status of the event",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "event_datetime",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Date and time when the event takes place",
                        verbose_name="event_datetime",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="created_at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="events.eventareamodel",
                        verbose_name="area",
                    ),
                ),
            ],
            options={
                "verbose_name": "event",
                "verbose_name_plural": "events",
                "db_table": "events",
                "ordering": ["-event_datetime", "name"],
            },
        ),
        migrations.CreateModel(
            name="VisitorModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="The visitor's full name",
                        max_length=255,
                        verbose_name="full_name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Contact email address for the visitor",
                        max_length=255,
                        verbose_name="email",
                    ),
                ),
                (
                    "registered_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="registered_at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "event_id",
                    models.ForeignKey(
                        db_column="event_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitors",
                        to="events.eventmodel",
                        verbose_name="event",
                    ),
                ),
            ],
            options={
                "verbose_name": "visitor",
                "verbose_name_plural": "visitors",
                "db_table": "visitors",
                "ordering": ["-registered_at"],
            },
        ),
        migrations.AddIndex(
            model_name="eventmodel",
            index=models.Index(
                fields=["status", "-event_datetime"],
                name="idx_status_datetime",
            ),
        ),
        migrations.AddIndex(
            model_name="eventmodel",
            index=models.Index(
                fields=["area", "-event_datetime"],
                name="idx_area_datetime",
            ),
        ),
        migrations.AddIndex(
            model_name="eventmodel",
            index=models.Index(fields=["-created_at"], name="idx_event_created_at"),
        ),
        migrations.AddIndex(
            model_name="visitormodel",
            index=models.Index(
                fields=["event_id", "-registered_at"],
                name="idx_visitor_event",
            ),
        ),
        migrations.AddIndex(
            model_name="visitormodel",
            index=models.Index(fields=["email"], name="idx_visitor_email"),
        ),
        migrations.AddConstraint(
            model_name="visitormodel",
            constraint=models.UniqueConstraint(
                fields=("event_id", "email"),
                name="unique_visitor_per_event",
            ),
        ),
    ]
